import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my website
        </h1>

        <div className={styles.grid}>
          <a href="/demo1" className={styles.card}>
            <h2>Demo 1</h2>
            <p>Fetch data from server.</p>
          </a>

          <a href="/demo2" className={styles.card}>
            <h2>Demo 2 &rarr;</h2>
            <p>Fetch data from client</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>About &rarr;</h2>
            <p>About me.</p>
          </a>

          <a
            href="https://docs.replit.com/category/hosting"
            className={styles.card}
          >
            <h2>Contact &rarr;</h2>
            <p>
              Contact me
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="/__repl"
          target="_blank"
          rel="noopener noreferrer"
        >
          Built on
          <span className={styles.logo}>
            <Image src="/replit.svg" alt="Replit Logo" width={20} height={18} />
          </span>
          Replit
        </a>
      </footer>
    </div>
  )
}

export default Home
